baseURL = "http://ramilfay.ru"
languageCode = "en-us"
title = "Ramil Fayzukhanov"
theme = "mini"

defaultContentLanguage = "en"
hasCJKLanguage = true

[permalinks]
posts = "/posts/:title/"

paginate = 3

#[[params.social]]
github = "https://github.com/fayramone"
#twitter = ""
#instagram = ""
#facebook = ""

[params]
author = "Ramil Fayzukhanov"
bio = "Verbal Poverty"
description = "I'm embrassing myself on the internet"

avatarLink = true
enableEmoji = true
enableRSS = false
enableComments = false
enableGoogleAnalytics = false
showToc = true
showPowerBy = true
math = false
hiddenPostSummaryInHomePage = false
copyright = "Ramil Fayzukhanov • © 2024 • Verbal Poverty"

[markup]
[markup.highlight]
guessSyntax = true
style = "emacs"

[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 2

[goldmark]
renderer = {unsafe= true}
